services:
  - type: web
    name: netscope-api
    env: java
    rootDir: java-packet-analyzer
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/java-packet-analyzer-1.0-SNAPSHOT.jar
    plan: free
